# Security Context properties
securityContext:
  # enabled is a flag to enable Security Context
  enabled: true
  # runAsUser is the user ID used to run the container
  runAsUser: 1000770000
  # runAsGroup is the primary group ID used to run all processes within any container of the pod
  runAsGroup: 1000770000
  # fsGroup is the group ID associated with the container
  fsGroup: 1000770000

hazelcast:
  javaOpts: -Dhazelcast.jmx=true -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600 -Dhazelcast.shutdownhook.policy=GRACEFUL
  yaml:
    hazelcast:
      properties:
        hazelcast.phone.home.enabled: false
      network:
        rest-api:
          enabled: true
          endpoint-groups:
            CLUSTER_READ:
              enabled: true
            CLUSTER_WRITE:
              enabled: true
            HEALTH_CHECK:
              enabled: true
            HOT_RESTART:
              enabled: true
            WAN:
              enabled: true
            DATA:
              enabled: true
  # configurationFiles are any additional Hazelcast configuration files
  # configurationFiles:

