# Security Context properties
securityContext:
  # enabled is a flag to enable Security Context
  enabled: true
  # runAsUser is the user ID used to run the container
  runAsUser: 1000770000
  # runAsGroup is the primary group ID used to run all processes within any container of the pod
  runAsGroup: 1000770000
  # fsGroup is the group ID associated with the container
  fsGroup: 1000770000

hazelcast:
  yaml:
    hazelcast:
      properties:
        hazelcast.phone.home.enabled: false
      network:
        rest-api:
          enabled: true
          endpoint-groups:
            CLUSTER_READ:
              enabled: true
            CLUSTER_WRITE:
              enabled: true
            HEALTH_CHECK:
              enabled: true
            HOT_RESTART:
              enabled: true
            WAN:
              enabled: true
            DATA:
              enabled: true
      hot-restart-persistence:
        enabled: ${hazelcast.hotRestart}
        base-dir: /data/hot-restart
        validation-timeout-seconds: 1200
        data-load-timeout-seconds: 900
        auto-remove-stale-data: true

  # configurationFiles are any additional Hazelcast configuration files
  # configurationFiles:

