apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: padogrid-template
  app: ${APP_NAME}
metadata:
  annotations:
    description: PadoGrid
  name: padogrid
  namespace: ${NAMESPACE}

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      name: ${APP_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${APP_NAME}
      spec:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
        containers:
        - image: docker.io/padogrid/padogrid
          name: padogrid
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HAZELCAST_SERVICE
            value: ${HAZELCAST_SERVICE}
parameters:
- description: The application name
  displayName: Application Name
  name: NAMESPACE
  required: true
  value: ${PROJECT_NAMESPACE}
- description: The application name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: padogrid
- description: Hazelcast service
  displayName: Hazelcast service
  name: HAZELCAST_SERVICE
  required: false
  value: hazelcast-enterprise
